In [6]:
b = [1,2,3]


In [16]:
b?

In [20]:
for number in b:
    print(number)
    
for number in b:
    if number > 2:
        print(number) 

1
2
3
3


In [3]:
a = "foo"
print(a.capitalize())
num = 56
num_as_str = str(num)
print(num_as_str)

Foo
56


In [9]:
True != False


True

In [10]:
5 != None

True

In [21]:
dt = datetime(2011,1,5,10)
print(dt.day)
print(dt.month)
print(dt.minute)
print(dt.year)

5
1
0
2011


In [23]:
for item in range(5,9):
    print(item)

5
6
7
8


In [24]:
list("a string")

['a', ' ', 's', 't', 'r', 'i', 'n', 'g']

In [26]:
"true" if True else "false"
"true" if False else "false"

'false'

In [37]:
tuple1 = tuple([1,2,3])
tuple2 = 4,5
tuple3 = tuple1, tuple2

print(tuple3)
a, b = tuple3

print(a)
print(b)


((1, 2, 3), (4, 5))
(1, 2, 3)
(4, 5)


In [74]:
myArray = [1,2,3]
myArray.append(4)
myArray.insert(2,0)
print(myArray)
myArray.sort()
print(myArray)
print(len(myArray))
3 in myArray

[1, 2, 0, 3, 4]
[0, 1, 2, 3, 4]
5


True

In [58]:
# dict = (same as associative array or hash map)
empty_dict = {}
empty_dict["name"] = "Mike"
empty_dict["email"] = "mike@test.com"
empty_dict["age"] = "50"
print(empty_dict)
print(empty_dict.keys())
print(empty_dict.values())
print("email" in empty_dict)
empty_dict.pop("email")
print("email" in empty_dict)

{'name': 'Mike', 'email': 'mike@test.com', 'age': '50'}
dict_keys(['name', 'email', 'age'])
dict_values(['Mike', 'mike@test.com', '50'])
True
False


In [63]:
# set = array with no duplicates
my_set1 = set([2,3,4,3])
print(my_set1)

my_set2 = set([4,5,6])
print(my_set1 & my_set2)
print(my_set1.union(my_set2))

{2, 3, 4}
{4}
{2, 3, 4, 5, 6}


In [73]:
# Functions - Must include return otherwise will return None. Supports keyword args and defaults
def add_number(a, b):
  return a + b

def multiply_number(a, b = 5):
  return a + b

def divide_number(a, b):
  return a / b

print(add_number(5, 9))
print(multiply_number(2))
print(divide_number(b = 3, a = 15))

type(add_number)

14
7
5.0


function

In [83]:
random_numbers = np.random.randn(3,5)

print(random_numbers)
print(random_numbers.shape)

[[ 0.75102913  0.52938204  1.09011891  0.47767664 -0.14108099]
 [ 1.17666856 -0.13251174  0.95101927  1.12754343 -0.38640726]
 [-0.5600253   0.06990633  1.1081656  -1.5337957   2.36424199]]
(3, 5)


In [88]:

myArray = [1,2,3,4]
numArray = np.array(myArray)
print(numArray)

np.zeros((2,6))



[1 2 3 4]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [91]:
myArray = ["Mike", "Laura", "Steve", "Jack", "Connor", "Mike"]
np.unique(np.array(myArray))


array(['Connor', 'Jack', 'Laura', 'Mike', 'Steve'], dtype='<U6')

In [93]:
samples = np.random.normal(size=(4,4))
print(samples)

[[-0.4381658   0.75407514  0.54603525 -0.45455049]
 [-1.22602764 -1.21152958 -0.09226953 -0.43266853]
 [ 1.02531216 -1.27785632 -0.56362971 -0.17438213]
 [ 0.5124822  -0.13507273  0.41609403 -0.21590879]]
