In [6]:
b = [1,2,3]


In [16]:
b?

In [20]:
for number in b:
    print(number)
    
for number in b:
    if number > 2:
        print(number) 

1
2
3
3


In [3]:
a = "foo"
print(a.capitalize())
num = 56
num_as_str = str(num)
print(num_as_str)

Foo
56


In [9]:
True != False


True

In [10]:
5 != None

True

In [21]:
dt = datetime(2011,1,5,10)
print(dt.day)
print(dt.month)
print(dt.minute)
print(dt.year)

5
1
0
2011


In [23]:
for item in range(5,9):
    print(item)

5
6
7
8


In [24]:
list("a string")

['a', ' ', 's', 't', 'r', 'i', 'n', 'g']

In [26]:
"true" if True else "false"
"true" if False else "false"

'false'

In [37]:
tuple1 = tuple([1,2,3])
tuple2 = 4,5
tuple3 = tuple1, tuple2

print(tuple3)
a, b = tuple3

print(a)
print(b)


((1, 2, 3), (4, 5))
(1, 2, 3)
(4, 5)


In [74]:
myArray = [1,2,3]
myArray.append(4)
myArray.insert(2,0)
print(myArray)
myArray.sort()
print(myArray)
print(len(myArray))
3 in myArray

[1, 2, 0, 3, 4]
[0, 1, 2, 3, 4]
5


True

In [58]:
# dict = (same as associative array or hash map)
empty_dict = {}
empty_dict["name"] = "Mike"
empty_dict["email"] = "mike@test.com"
empty_dict["age"] = "50"
print(empty_dict)
print(empty_dict.keys())
print(empty_dict.values())
print("email" in empty_dict)
empty_dict.pop("email")
print("email" in empty_dict)

{'name': 'Mike', 'email': 'mike@test.com', 'age': '50'}
dict_keys(['name', 'email', 'age'])
dict_values(['Mike', 'mike@test.com', '50'])
True
False


In [63]:
# set = array with no duplicates
my_set1 = set([2,3,4,3])
print(my_set1)

my_set2 = set([4,5,6])
print(my_set1 & my_set2)
print(my_set1.union(my_set2))

{2, 3, 4}
{4}
{2, 3, 4, 5, 6}


In [73]:
# Functions - Must include return otherwise will return None. Supports keyword args and defaults
def add_number(a, b):
  return a + b

def multiply_number(a, b = 5):
  return a + b

def divide_number(a, b):
  return a / b

print(add_number(5, 9))
print(multiply_number(2))
print(divide_number(b = 3, a = 15))

type(add_number)

14
7
5.0


function

In [94]:
random_numbers = np.random.randn(3,5)

print(random_numbers)
print(random_numbers.shape)

[[-1.42467329 -1.27010547 -0.79997512 -1.20952745 -0.17728024]
 [ 0.32175968  0.20773879  1.19746464  0.10882268 -0.73107554]
 [ 1.57063192  0.01406196 -0.91612118  0.4307806  -0.20907388]]
(3, 5)


In [95]:
myArray = [1,2,3,4]
numArray = np.array(myArray)
print(numArray)

np.zeros((2,6))



[1 2 3 4]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [91]:
myArray = ["Mike", "Laura", "Steve", "Jack", "Connor", "Mike"]
np.unique(np.array(myArray))


array(['Connor', 'Jack', 'Laura', 'Mike', 'Steve'], dtype='<U6')

In [96]:
samples = np.random.normal(size=(4,4))
print(samples)b

[[ 1.42701869e+00  3.60336712e-01  2.10562507e-01 -5.65974514e-02]
 [ 9.72518410e-01 -5.07363442e-01  7.17731235e-04 -2.58310004e+00]
 [ 6.04762647e-01 -9.60237531e-01 -8.92334867e-01 -1.43786335e-01]
 [-6.93766652e-01 -2.51007661e+00  7.21510094e-01  2.37627100e-01]]


In [179]:
# Pandas - best for tabular and homogeneous data
# Series and DataFrame
# Series is one dimensional array
# DataFrame = rectuangular dataset

import pandas as pd

data = {'state': ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
       }

frame = pd.DataFrame(data, columns=["state", "pop", "year", "status"])
print(frame.head())

# sorting
print(frame.sort_values(by="pop"))

frame.status = "Unknown"
print(frame.head())

# Transpose
print(frame.T)

# drop
print(frame.drop([2,4]))

    state  pop  year status
0    Ohio  1.5  2000    NaN
1    Ohio  1.7  2001    NaN
2    Ohio  3.6  2002    NaN
3  Nevada  2.4  2001    NaN
4  Nevada  2.9  2002    NaN
    state  pop  year status
0    Ohio  1.5  2000    NaN
1    Ohio  1.7  2001    NaN
3  Nevada  2.4  2001    NaN
4  Nevada  2.9  2002    NaN
5  Nevada  3.2  2003    NaN
2    Ohio  3.6  2002    NaN
    state  pop  year   status
0    Ohio  1.5  2000  Unknown
1    Ohio  1.7  2001  Unknown
2    Ohio  3.6  2002  Unknown
3  Nevada  2.4  2001  Unknown
4  Nevada  2.9  2002  Unknown
              0        1        2        3        4        5
state      Ohio     Ohio     Ohio   Nevada   Nevada   Nevada
pop         1.5      1.7      3.6      2.4      2.9      3.2
year       2000     2001     2002     2001     2002     2003
status  Unknown  Unknown  Unknown  Unknown  Unknown  Unknown
    state  pop  year   status
0    Ohio  1.5  2000  Unknown
1    Ohio  1.7  2001  Unknown
3  Nevada  2.4  2001  Unknown
5  Nevada  3.2  2003  Unknown


In [116]:
print(frame.describe())

            pop         year
count  6.000000     6.000000
mean   2.550000  2001.500000
std    0.836062     1.048809
min    1.500000  2000.000000
25%    1.875000  2001.000000
50%    2.650000  2001.500000
75%    3.125000  2002.000000
max    3.600000  2003.000000


In [151]:
user_data = pd.read_csv("./data/users.csv")

user_data.columns

Index(['id', 'email', 'encrypted_password', 'confirmation_token',
       'remember_token', 'legacy_uuid', 'first_name', 'last_name',
       'legacy_candidate_id', 'created_at', 'updated_at', 'phone_number',
       'headline', 'facebook_username', 'linkedin_username',
       'twitter_username', 'gender', 'military_status', 'race',
       'last_signed_in_at', 'admin', 'marketable', 'legacy_resume_exists',
       'professional_networkable', 'deleted_at', 'legacy_profile_photo_exists',
       'apns_token'],
      dtype='object')

In [178]:
# data from an api
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

resp = requests.get(url)
url_data = resp.json()
url_data[0]['user']['login']

'dhimmel'

In [157]:
columns_of_interest = ["email", "last_signed_in_at"]
subset = user_data[columns_of_interest]
print(subset.describe())
print(subset.head())

# This is dropping rows, not columns
dropped = subset.dropna(how="any")
print(dropped.head())

       last_signed_in_at
count                0.0
mean                 NaN
std                  NaN
min                  NaN
25%                  NaN
50%                  NaN
75%                  NaN
max                  NaN
                   email  last_signed_in_at
0      admin@example.com                NaN
1   reviewer@example.com                NaN
2  candidate@example.com                NaN
3     user+1@example.com                NaN
4     user+2@example.com                NaN
Empty DataFrame
Columns: [email, last_signed_in_at]
Index: []


In [162]:
columns_of_interest = ["email", "last_signed_in_at"]
subset2 = user_data[columns_of_interest]

# Fill empty values
subset2.fillna(5)

# drop duplicates
print(subset2.head())
subset2.duplicated()
subset2.drop_duplicates()


                   email  last_signed_in_at
0      admin@example.com                NaN
1   reviewer@example.com                NaN
2  candidate@example.com                NaN
3     user+1@example.com                NaN
4     user+2@example.com                NaN


email  last_signed_in_at
0        admin@example.com                NaN
1     reviewer@example.com                NaN
2    candidate@example.com                NaN
3       user+1@example.com                NaN
4       user+2@example.com                NaN
5       user+4@example.com                NaN
6       user+5@example.com                NaN
7       user+6@example.com                NaN
8      user+18@example.com                NaN
9       user+8@example.com                NaN
10      user+3@example.com                NaN
11     user+10@example.com                NaN
12     user+11@example.com                NaN
13     user+12@example.com                NaN
14     user+14@example.com                NaN
15      user+9@example.com                NaN
16     user+16@example.com                NaN
17     user+17@example.com                NaN
18     user+23@example.com                NaN
19     user+20@example.com                NaN
20     user+15@example.com                NaN
21     user+22@example.com                NaN
22     user+24@example.com                NaN
23     user+26@example.com                NaN
24     user+21@example.com                NaN
25     user+28@example.com                NaN
26     user+29@example.com                NaN
27     user+30@example.com                NaN
28     user+32@example.com                NaN
29     user+27@example.com                NaN
..                     ...                ...
676   user+806@example.com                NaN
677   user+811@example.com                NaN
678   user+803@example.com                NaN
679   user+809@example.com                NaN
680   user+815@example.com                NaN
681   user+808@example.com                NaN
682   user+814@example.com                NaN
683   user+816@example.com                NaN
684   user+828@example.com                NaN
685   user+813@example.com                NaN
686   user+819@example.com                NaN
687   user+820@example.com                NaN
688   user+821@example.com                NaN
689   user+834@example.com                NaN
690   user+818@example.com                NaN
691   user+824@example.com                NaN
692   user+825@example.com                NaN
693   user+826@example.com                NaN
694   user+835@example.com                NaN
695   user+823@example.com                NaN
696   user+829@example.com                NaN
697   user+830@example.com                NaN
698   user+831@example.com                NaN
699   user+840@example.com                NaN
700   user+836@example.com                NaN
701   user+841@example.com                NaN
702   user+833@example.com                NaN
703   user+839@example.com                NaN
704   employer@example.com                NaN
705   user+838@example.com                NaN

[706 rows x 2 columns]

In [163]:
# Replace bad data with correct value
user_data.replace(-999, np.NAN)

id                  email  \
0      1      admin@example.com   
1      3   reviewer@example.com   
2      4  candidate@example.com   
3      5     user+1@example.com   
4      6     user+2@example.com   
5      7     user+4@example.com   
6      8     user+5@example.com   
7      9     user+6@example.com   
8     19    user+18@example.com   
9     11     user+8@example.com   
10    10     user+3@example.com   
11    12    user+10@example.com   
12    13    user+11@example.com   
13    14    user+12@example.com   
14    16    user+14@example.com   
15    15     user+9@example.com   
16    17    user+16@example.com   
17    18    user+17@example.com   
18    23    user+23@example.com   
19    21    user+20@example.com   
20    20    user+15@example.com   
21    22    user+22@example.com   
22    24    user+24@example.com   
23    26    user+26@example.com   
24    25    user+21@example.com   
25    27    user+28@example.com   
26    28    user+29@example.com   
27    29    user+30@example.com   
28    31    user+32@example.com   
29    30    user+27@example.com   
..   ...                    ...   
676  677   user+806@example.com   
677  681   user+811@example.com   
678  678   user+803@example.com   
679  679   user+809@example.com   
680  684   user+815@example.com   
681  682   user+808@example.com   
682  683   user+814@example.com   
683  685   user+816@example.com   
684  698   user+828@example.com   
685  686   user+813@example.com   
686  687   user+819@example.com   
687  688   user+820@example.com   
688  689   user+821@example.com   
689  699   user+834@example.com   
690  690   user+818@example.com   
691  691   user+824@example.com   
692  692   user+825@example.com   
693  693   user+826@example.com   
694  700   user+835@example.com   
695  694   user+823@example.com   
696  695   user+829@example.com   
697  696   user+830@example.com   
698  697   user+831@example.com   
699  704   user+840@example.com   
700  701   user+836@example.com   
701  705   user+841@example.com   
702  702   user+833@example.com   
703  703   user+839@example.com   
704    2   employer@example.com   
705  706   user+838@example.com   

                                    encrypted_password  confirmation_token  \
0    $2a$10$T0wZEFd2JbQN85MpDv23mOIBS8lCfAvziP7dq7H...                 NaN   
1    $2a$10$MMO0RTfsu5X.Dj.nu.eyqeLVpYTYTYZvyl6QJPd...                 NaN   
2    $2a$10$fOv2laVSpM4SRQxDC67iHOyDGgKs8PYEWgWRn4h...                 NaN   
3    $2a$10$Opasz4lDvhIfN5slJfRa1.676yi3bc9T2chczuI...                 NaN   
4    $2a$10$vW.koBUSaPvtIMMgC5JWzeIUzKjd.V0ngKoQMoH...                 NaN   
5    $2a$10$kmC6EBwdObiLhbJjEYqSBu6O0xI7qHJQpdGZu5....                 NaN   
6    $2a$10$.2VGP5vlUmTs1aYXYP0p/ec5urdABYl16GRtNEG...                 NaN   
7    $2a$10$xyzrxYtsdcU5Syz1vUNJbe4dCgZ4ZWysGut3sIG...                 NaN   
8    $2a$10$nWaBq5zZ/NPhqaJZ51FVKOdhz./Rbxljbdleep5...                 NaN   
9    $2a$10$F/hLKnH6zCNJu62f3vR46uWwsWKn3zQUs8c5.3b...                 NaN   
10   $2a$10$s959FmEiiPf3QnBjqJ934u/KtrM/eU5x4Qx5azp...                 NaN   
11   $2a$10$2.JJ4jAuasMRnEh.HaXOS.8Ak4r.gUkdf2f1zn7...                 NaN   
12   $2a$10$QjUu/4f7/gsEDk2Iwd2l9etvQ54J40FIlH97ZeU...                 NaN   
13   $2a$10$XdGG2vXPwJtjMLxHGmwweufhhDAHIo5q/MKRVgU...                 NaN   
14   $2a$10$GsN25mkn6O3iWNUZPxlcleDqpoFhjZCOVOgQcPg...                 NaN   
15   $2a$10$RYNUKjujskIER97TkPJ3kucLILPe6Qf0gwOHIj3...                 NaN   
16   $2a$10$K9tN5k9grTSYSaKKxVxiIu3oQ/kGdcyy2ZStoGF...                 NaN   
17   $2a$10$0IKHiUv5pZ1I9QZP9JGF7O7XMTXUcaUssDCWGeG...                 NaN   
18   $2a$10$.XiNQPY6DhP0BcttgNjwsu7njlWKTEL6gzvre0n...                 NaN   
19   $2a$10$lrwuZ4DKtHtYIa8JHXpWG.DEiY.PRPrxbowPWUt...                 NaN   
20   $2a$10$ZKblKIF10GaFQbF.mewPS.EFaoxfbFbRGpk6f0m...                 NaN   
21   $2a$10$dODxJWD4BdmlHgQuy/gfUuuChphsmz37tyCwk1y...                 NaN   
22   $2a$10$A3xI.ILn3CD0QMKURUwzyu0OG.Wsi

In [164]:
# rename columns
user_data.rename(columns={"email": "user_email"})

id             user_email  \
0      1      admin@example.com   
1      3   reviewer@example.com   
2      4  candidate@example.com   
3      5     user+1@example.com   
4      6     user+2@example.com   
5      7     user+4@example.com   
6      8     user+5@example.com   
7      9     user+6@example.com   
8     19    user+18@example.com   
9     11     user+8@example.com   
10    10     user+3@example.com   
11    12    user+10@example.com   
12    13    user+11@example.com   
13    14    user+12@example.com   
14    16    user+14@example.com   
15    15     user+9@example.com   
16    17    user+16@example.com   
17    18    user+17@example.com   
18    23    user+23@example.com   
19    21    user+20@example.com   
20    20    user+15@example.com   
21    22    user+22@example.com   
22    24    user+24@example.com   
23    26    user+26@example.com   
24    25    user+21@example.com   
25    27    user+28@example.com   
26    28    user+29@example.com   
27    29    user+30@example.com   
28    31    user+32@example.com   
29    30    user+27@example.com   
..   ...                    ...   
676  677   user+806@example.com   
677  681   user+811@example.com   
678  678   user+803@example.com   
679  679   user+809@example.com   
680  684   user+815@example.com   
681  682   user+808@example.com   
682  683   user+814@example.com   
683  685   user+816@example.com   
684  698   user+828@example.com   
685  686   user+813@example.com   
686  687   user+819@example.com   
687  688   user+820@example.com   
688  689   user+821@example.com   
689  699   user+834@example.com   
690  690   user+818@example.com   
691  691   user+824@example.com   
692  692   user+825@example.com   
693  693   user+826@example.com   
694  700   user+835@example.com   
695  694   user+823@example.com   
696  695   user+829@example.com   
697  696   user+830@example.com   
698  697   user+831@example.com   
699  704   user+840@example.com   
700  701   user+836@example.com   
701  705   user+841@example.com   
702  702   user+833@example.com   
703  703   user+839@example.com   
704    2   employer@example.com   
705  706   user+838@example.com   

                                    encrypted_password  confirmation_token  \
0    $2a$10$T0wZEFd2JbQN85MpDv23mOIBS8lCfAvziP7dq7H...                 NaN   
1    $2a$10$MMO0RTfsu5X.Dj.nu.eyqeLVpYTYTYZvyl6QJPd...                 NaN   
2    $2a$10$fOv2laVSpM4SRQxDC67iHOyDGgKs8PYEWgWRn4h...                 NaN   
3    $2a$10$Opasz4lDvhIfN5slJfRa1.676yi3bc9T2chczuI...                 NaN   
4    $2a$10$vW.koBUSaPvtIMMgC5JWzeIUzKjd.V0ngKoQMoH...                 NaN   
5    $2a$10$kmC6EBwdObiLhbJjEYqSBu6O0xI7qHJQpdGZu5....                 NaN   
6    $2a$10$.2VGP5vlUmTs1aYXYP0p/ec5urdABYl16GRtNEG...                 NaN   
7    $2a$10$xyzrxYtsdcU5Syz1vUNJbe4dCgZ4ZWysGut3sIG...                 NaN   
8    $2a$10$nWaBq5zZ/NPhqaJZ51FVKOdhz./Rbxljbdleep5...                 NaN   
9    $2a$10$F/hLKnH6zCNJu62f3vR46uWwsWKn3zQUs8c5.3b...                 NaN   
10   $2a$10$s959FmEiiPf3QnBjqJ934u/KtrM/eU5x4Qx5azp...                 NaN   
11   $2a$10$2.JJ4jAuasMRnEh.HaXOS.8Ak4r.gUkdf2f1zn7...                 NaN   
12   $2a$10$QjUu/4f7/gsEDk2Iwd2l9etvQ54J40FIlH97ZeU...                 NaN   
13   $2a$10$XdGG2vXPwJtjMLxHGmwweufhhDAHIo5q/MKRVgU...                 NaN   
14   $2a$10$GsN25mkn6O3iWNUZPxlcleDqpoFhjZCOVOgQcPg...                 NaN   
15   $2a$10$RYNUKjujskIER97TkPJ3kucLILPe6Qf0gwOHIj3...                 NaN   
16   $2a$10$K9tN5k9grTSYSaKKxVxiIu3oQ/kGdcyy2ZStoGF...                 NaN   
17   $2a$10$0IKHiUv5pZ1I9QZP9JGF7O7XMTXUcaUssDCWGeG...                 NaN   
18   $2a$10$.XiNQPY6DhP0BcttgNjwsu7njlWKTEL6gzvre0n...                 NaN   
19   $2a$10$lrwuZ4DKtHtYIa8JHXpWG.DEiY.PRPrxbowPWUt...                 NaN   
20   $2a$10$ZKblKIF10GaFQbF.mewPS.EFaoxfbFbRGpk6f0m...                 NaN   
21   $2a$10$dODxJWD4BdmlHgQuy/gfUuuChphsmz37tyCwk1y...                 NaN   
22   $2a$10$A3xI.ILn3CD0QMKURUwzyu0OG.Wsi

In [173]:
# Search table for string
user_data[user_data.email.str.contains("reviewer")]

id                 email  \
1   3  reviewer@example.com   

                                  encrypted_password  confirmation_token  \
1  $2a$10$MMO0RTfsu5X.Dj.nu.eyqeLVpYTYTYZvyl6QJPd...                 NaN   

                             remember_token  \
1  83f6a0a68bc21451082747617123c01b1e03e347   

                            legacy_uuid first_name last_name  \
1  57142dae-a1df-4809-8fed-c9c45e8d7055   Serena-3  Reviewer   

   legacy_candidate_id created_at     ...     military_status  race  \
1                    3    06:32.2     ...                 NaN   NaN   

  last_signed_in_at admin marketable legacy_resume_exists  \
1               NaN     f          f                    f   

   professional_networkable  deleted_at  legacy_profile_photo_exists  \
1                         t         NaN                            f   

   apns_token  
1       token  

[1 rows x 27 columns]

In [176]:
import re
# Search table for string
user_data[user_data.email.str.match(re.compile("reviewer|admin|candidate"))]

id                  email  \
0   1      admin@example.com   
1   3   reviewer@example.com   
2   4  candidate@example.com   

                                  encrypted_password  confirmation_token  \
0  $2a$10$T0wZEFd2JbQN85MpDv23mOIBS8lCfAvziP7dq7H...                 NaN   
1  $2a$10$MMO0RTfsu5X.Dj.nu.eyqeLVpYTYTYZvyl6QJPd...                 NaN   
2  $2a$10$fOv2laVSpM4SRQxDC67iHOyDGgKs8PYEWgWRn4h...                 NaN   

                             remember_token  \
0  443f399785737bd175a6ba6f9f1a0b3f6e51462f   
1  83f6a0a68bc21451082747617123c01b1e03e347   
2  2c5c616a47fd250dbf0f512080761d76aa8ad2ad   

                            legacy_uuid first_name  last_name  \
0  f1bcf436-944a-48f5-8e95-25993f484359   Serena-1   Williams   
1  57142dae-a1df-4809-8fed-c9c45e8d7055   Serena-3   Reviewer   
2  b918d277-2043-4ea8-ada2-5b85f5affb59   Serena-4  Candidate   

   legacy_candidate_id created_at     ...     military_status  race  \
0                    1    06:30.8     ...                 NaN   NaN   
1                    3    06:32.2     ...                 NaN   NaN   
2                    4    06:32.3     ...                 NaN   NaN   

  last_signed_in_at admin marketable legacy_resume_exists  \
0               NaN     t          f                    f   
1               NaN     f          f                    f   
2               NaN     f          f                    f   

   professional_networkable  deleted_at  legacy_profile_photo_exists  \
0                         t         NaN                            f   
1                         t         NaN                            f   
2                         t         NaN                            f   

   apns_token  
0       token  
1       token  
2       token  

[3 rows x 27 columns]

In [194]:
# merging data 

new_frame = pd.DataFrame(new_data)
print(new_frame.merge(frame))


    state  year  pop   status
0    Ohio  2000  1.5  Unknown
1    Ohio  2001  1.7  Unknown
2    Ohio  2002  3.6  Unknown
3  Nevada  2001  2.4  Unknown
4  Nevada  2002  2.9  Unknown
5  Nevada  2003  3.2  Unknown
