In [6]:
b = [1,2,3]


In [16]:
b?

In [20]:
for number in b:
    print(number)
    
for number in b:
    if number > 2:
        print(number) 

1
2
3
3


In [3]:
a = "foo"
print(a.capitalize())
num = 56
num_as_str = str(num)
print(num_as_str)

Foo
56


In [9]:
True != False


True

In [10]:
5 != None

True

In [21]:
dt = datetime(2011,1,5,10)
print(dt.day)
print(dt.month)
print(dt.minute)
print(dt.year)

5
1
0
2011


In [23]:
for item in range(5,9):
    print(item)

5
6
7
8


In [24]:
list("a string")

['a', ' ', 's', 't', 'r', 'i', 'n', 'g']

In [26]:
"true" if True else "false"
"true" if False else "false"

'false'

In [37]:
tuple1 = tuple([1,2,3])
tuple2 = 4,5
tuple3 = tuple1, tuple2

print(tuple3)
a, b = tuple3

print(a)
print(b)


((1, 2, 3), (4, 5))
(1, 2, 3)
(4, 5)


In [74]:
myArray = [1,2,3]
myArray.append(4)
myArray.insert(2,0)
print(myArray)
myArray.sort()
print(myArray)
print(len(myArray))
3 in myArray

[1, 2, 0, 3, 4]
[0, 1, 2, 3, 4]
5


True

In [58]:
# dict = (same as associative array or hash map)
empty_dict = {}
empty_dict["name"] = "Mike"
empty_dict["email"] = "mike@test.com"
empty_dict["age"] = "50"
print(empty_dict)
print(empty_dict.keys())
print(empty_dict.values())
print("email" in empty_dict)
empty_dict.pop("email")
print("email" in empty_dict)

{'name': 'Mike', 'email': 'mike@test.com', 'age': '50'}
dict_keys(['name', 'email', 'age'])
dict_values(['Mike', 'mike@test.com', '50'])
True
False


In [63]:
# set = array with no duplicates
my_set1 = set([2,3,4,3])
print(my_set1)

my_set2 = set([4,5,6])
print(my_set1 & my_set2)
print(my_set1.union(my_set2))

{2, 3, 4}
{4}
{2, 3, 4, 5, 6}


In [73]:
# Functions - Must include return otherwise will return None. Supports keyword args and defaults
def add_number(a, b):
  return a + b

def multiply_number(a, b = 5):
  return a + b

def divide_number(a, b):
  return a / b

print(add_number(5, 9))
print(multiply_number(2))
print(divide_number(b = 3, a = 15))

type(add_number)

14
7
5.0


function

In [94]:
random_numbers = np.random.randn(3,5)

print(random_numbers)
print(random_numbers.shape)

[[-1.42467329 -1.27010547 -0.79997512 -1.20952745 -0.17728024]
 [ 0.32175968  0.20773879  1.19746464  0.10882268 -0.73107554]
 [ 1.57063192  0.01406196 -0.91612118  0.4307806  -0.20907388]]
(3, 5)


In [95]:
myArray = [1,2,3,4]
numArray = np.array(myArray)
print(numArray)

np.zeros((2,6))



[1 2 3 4]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [91]:
myArray = ["Mike", "Laura", "Steve", "Jack", "Connor", "Mike"]
np.unique(np.array(myArray))


array(['Connor', 'Jack', 'Laura', 'Mike', 'Steve'], dtype='<U6')

In [96]:
samples = np.random.normal(size=(4,4))
print(samples)b

[[ 1.42701869e+00  3.60336712e-01  2.10562507e-01 -5.65974514e-02]
 [ 9.72518410e-01 -5.07363442e-01  7.17731235e-04 -2.58310004e+00]
 [ 6.04762647e-01 -9.60237531e-01 -8.92334867e-01 -1.43786335e-01]
 [-6.93766652e-01 -2.51007661e+00  7.21510094e-01  2.37627100e-01]]


In [111]:
# Pandas - best for tabular and homogeneous data
# Series and DataFrame
# Series is one dimensional array
# DataFrame = rectuangular dataset

import pandas as pd

data = {'state': ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
       }

frame = pd.DataFrame(data, columns=["state", "pop", "year", "status"])
print(frame.head())

# sorting
print(frame.sort_values(by="pop"))

frame.status = "Unknown"
print(frame.head())

# Transpose
print(frame.T)

# drop
print(frame.drop([2,4]))

    state  pop  year status
0    Ohio  1.5  2000    NaN
1    Ohio  1.7  2001    NaN
2    Ohio  3.6  2002    NaN
3  Nevada  2.4  2001    NaN
4  Nevada  2.9  2002    NaN
    state  pop  year status
0    Ohio  1.5  2000    NaN
1    Ohio  1.7  2001    NaN
3  Nevada  2.4  2001    NaN
4  Nevada  2.9  2002    NaN
5  Nevada  3.2  2003    NaN
2    Ohio  3.6  2002    NaN
    state  pop  year   status
0    Ohio  1.5  2000  Unknown
1    Ohio  1.7  2001  Unknown
2    Ohio  3.6  2002  Unknown
3  Nevada  2.4  2001  Unknown
4  Nevada  2.9  2002  Unknown
              0        1        2        3        4        5
state      Ohio     Ohio     Ohio   Nevada   Nevada   Nevada
pop         1.5      1.7      3.6      2.4      2.9      3.2
year       2000     2001     2002     2001     2002     2003
status  Unknown  Unknown  Unknown  Unknown  Unknown  Unknown
    state  pop  year   status
0    Ohio  1.5  2000  Unknown
1    Ohio  1.7  2001  Unknown
3  Nevada  2.4  2001  Unknown
5  Nevada  3.2  2003  Unknown


In [116]:
print(frame.describe())

            pop         year
count  6.000000     6.000000
mean   2.550000  2001.500000
std    0.836062     1.048809
min    1.500000  2000.000000
25%    1.875000  2001.000000
50%    2.650000  2001.500000
75%    3.125000  2002.000000
max    3.600000  2003.000000


In [151]:
user_data = pd.read_csv("./data/users.csv")

user_data.columns

Index(['id', 'email', 'encrypted_password', 'confirmation_token',
       'remember_token', 'legacy_uuid', 'first_name', 'last_name',
       'legacy_candidate_id', 'created_at', 'updated_at', 'phone_number',
       'headline', 'facebook_username', 'linkedin_username',
       'twitter_username', 'gender', 'military_status', 'race',
       'last_signed_in_at', 'admin', 'marketable', 'legacy_resume_exists',
       'professional_networkable', 'deleted_at', 'legacy_profile_photo_exists',
       'apns_token'],
      dtype='object')

In [133]:
# data from an api
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

resp = requests.get(url)
data = resp.json()
data[0]['user']['login']

'dhimmel'

In [157]:
columns_of_interest = ["email", "last_signed_in_at"]
subset = user_data[columns_of_interest]
print(subset.describe())
print(subset.head())

# This is dropping rows, not columns
dropped = subset.dropna(how="any")
print(dropped.head())

       last_signed_in_at
count                0.0
mean                 NaN
std                  NaN
min                  NaN
25%                  NaN
50%                  NaN
75%                  NaN
max                  NaN
                   email  last_signed_in_at
0      admin@example.com                NaN
1   reviewer@example.com                NaN
2  candidate@example.com                NaN
3     user+1@example.com                NaN
4     user+2@example.com                NaN
Empty DataFrame
Columns: [email, last_signed_in_at]
Index: []
